name: Shoe Price Tracker

on:
  # schedule:
  #   - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents:  write   # allow pushing commits

jobs:
  run-tracker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses:  actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run tracker
        run: python shoe_tracker.py
        env:
          BOT_TOKEN:  ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}

      - name: Upload status page
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html last_price.txt
          git commit -m "Update status page"
          git push
